name: oxoo
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
#  sdk: ">=2.10.4 <3.0.0"
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  admob_flutter: ^2.0.0-nullsafety.1
  app_review: ^2.1.1+1
  built_value: ^8.1.1
  carousel_slider: ^4.0.0
  chewie: ^1.0.0
  country_code_picker: ^2.0.2
  credit_card_input_form: ^2.3.0
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  equatable: ^2.0.3
  firebase_auth: ^2.0.0
  firebase_core: ^1.3.0
  flutter_bloc: ^7.0.1
  flutter_downloader: ^1.6.1
  flutter_facebook_auth: ^3.5.0
  flutter_keyboard_visibility: ^5.0.2
  #flutter_mdns_plugin: ^0.0.1
  flutter_pagewise: ^2.0.1
  #flutter_playout: ^2.0.1
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.7
  get_it: ^7.1.3
  google_sign_in: ^5.0.4
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.3
  image_picker: ^0.8.1+3
  in_app_purchase: ^0.4.0
  meta: ^1.3.0
  moor: ^4.4.1
  onesignal_flutter: ^3.0.0
  permission_handler: ^8.1.2
  pinput: ^1.2.0
  provider: ^5.0.0
  share: ^2.0.4
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  sign_in_with_apple: ^3.0.0
  url_launcher: ^6.0.9
  video_player: ^2.0.0
  webview_flutter: ^2.0.9
  youtube_player_flutter: ^8.0.0
#  youtube_player_flutter: ^7.0.0+7

dev_dependencies:
#  sdk: flutter
#  flutter_test: any

  build_runner: ^2.0.6
  flutter_launcher_icons: ^0.9.0
  hive_generator: ^1.1.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/android_launcher_icon.jpg"
  bloc_test: ^3.0.0

dependency_overrides: null
#analyzer: ^0.41.0
flutter:
  uses-material-design: true
  assets:
    - assets/splash_image.png
    - assets/logo.png
    - assets/android_launcher_icon.jpg
    - assets/drawer_icon/
    - assets/images/
    - assets/bottom_nav/
    - assets/images/ic_button_apple.png
    - assets/srishakti_intro.mp4
